### ISSUE TITLE
authn issue when using com.sixsq.slipstream.tools.cli.ssconfigdump

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#1140]
This came out during generation of the reference configuration.

```
$ sh -x ./server-config-dump.sh -s nuv.la -p XXX -n admin:siXsQ2013 -w
...
+ java -cp SlipStreamToolsCli.jar com.sixsq.slipstream.tools.cli.ssconfigdump -s super:XXX -x https://nuv.la --skip-no-connector-name -m 'nuv.la=<CHANGE_HOSTNAME>' -m '185.19.28.68=<CHANGE_HOSTNAME>'
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" clojure.lang.ExceptionInfo: clj-http: status 401 {:request-time 721, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :reason-phrase "Unauthorized", :headers {"Server" "nginx", "Date" "Mon, 07 Aug 2017 09:48:53 GMT", "Content-Type" "application/xml; charset=UTF-8", "Content-Length" "224", "Connection" "close", "Accept-Ranges" "bytes", "Set-Cookie" "com.sixsq.slipstream.cookie=INVALID; Path=/; Expires=Mon, 07 Aug 2017 09:48:53 GMT", "Strict-Transport-Security" "max-age=31536000; includeSubdomains"}, :orig-content-encoding nil, :status 401, :length 224, :body "<error code=\"401\" reason=\"Unauthorized\" detail=\"The request requires user authentication\" specificationUri=\"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2\">\nThe request requires user authentication\n</error>"}
        at slingshot.support$stack_trace.invoke(support.clj:201)
        at clj_http.client$wrap_exceptions$fn__1828.invoke(client.clj:226)
        at clj_http.client$wrap_accept$fn__1992.invoke(client.clj:593)
        at clj_http.client$wrap_accept_encoding$fn__1998.invoke(client.clj:610)
        at clj_http.client$wrap_content_type$fn__1987.invoke(client.clj:586)
        at clj_http.client$wrap_form_params$fn__2077.invoke(client.clj:766)
        at clj_http.client$wrap_nested_params$fn__2098.invoke(client.clj:791)
        at clj_http.client$wrap_method$fn__2047.invoke(client.clj:708)
        at clj_http.cookies$wrap_cookies$fn__639.invoke(cookies.clj:124)
        at clj_http.links$wrap_links$fn__1641.invoke(links.clj:51)
        at clj_http.client$wrap_unknown_host$fn__2107.invoke(client.clj:811)
        at clj_http.client$get.invokeStatic(client.clj:914)
        at clj_http.client$get.doInvoke(client.clj:910)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at com.sixsq.slipstream.tools.cli.utils$conf_xml.invokeStatic(utils.clj:74)
        at com.sixsq.slipstream.tools.cli.utils$conf_xml.invoke(utils.clj:69)
        at com.sixsq.slipstream.tools.cli.utils$cfg_path_url__GT_sc.invokeStatic(utils.clj:83)
        at com.sixsq.slipstream.tools.cli.utils$cfg_path_url__GT_sc.invoke(utils.clj:80)
        at com.sixsq.slipstream.tools.cli.ssconfigdump$run.invokeStatic(ssconfigdump.clj:56)
        at com.sixsq.slipstream.tools.cli.ssconfigdump$run.invoke(ssconfigdump.clj:54)
        at com.sixsq.slipstream.tools.cli.ssconfigdump$_main.invokeStatic(ssconfigdump.clj:116)
        at com.sixsq.slipstream.tools.cli.ssconfigdump$_main.doInvoke(ssconfigdump.clj:99)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at com.sixsq.slipstream.tools.cli.ssconfigdump.main(Unknown Source)
$
```

**Comment by konstan** [comment]
Closing as invalid.  There was a typo in password.
