### ISSUE TITLE
define cron process to insert global state

### ISSUE THREAD

**Issue by elegoff** [slipstream/SlipStreamServer#1190]
As part of https://github.com/SixSq/tasklist/issues/1302, we need a one minute process responsible for 
- Fetching the current global state 
- Inserting the documents (one by one until the bulk update API is available) into a dedicated resource (TODO : define resource name)

This inserted resource will be the basis of accounting calculations through aggregation queries

**Comment by loomis** [comment]
The deployment of the metering service on the Elasticsearch node for Nuvla eventually caused the Elasticsearch database to crash. The error messages from the metering journal are similar to the following:
```
Exception in thread "async-dispatch-80" java.lang.IllegalStateException: org.apache.http.nio.reactor.IOReactorException: Failure opening selector
at org.apache.http.impl.nio.client.IOReactorUtils.create(IOReactorUtils.java:45)
at org.apache.http.impl.nio.client.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:666)
at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:202)
at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:180)
at qbits.spandex.client_options$builder.invokeStatic(client_options.clj:197)
at qbits.spandex.client_options$builder.invoke(client_options.clj:192)
at qbits.spandex$client.invokeStatic(spandex.clj:83)
at qbits.spandex$client.invoke(spandex.clj:33)
at com.sixsq.slipstream.metering$fetch_global_state$fn__12058$state_machine__7262__auto____12061$fn__12063.invoke(metering.clj:55)
at com.sixsq.slipstream.metering$fetch_global_state$fn__12058$state_machine__7262__auto____12061.invoke(metering.clj:50)
at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
at com.sixsq.slipstream.metering$fetch_global_state$fn__12058.invoke(metering.clj:50)
at clojure.lang.AFn.run(AFn.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.nio.reactor.IOReactorException: Failure opening selector
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:144)
at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:79)
at org.apache.http.impl.nio.client.IOReactorUtils.create(IOReactorUtils.java:43)
... 18 more
Caused by: java.io.IOException: Too many open files
at sun.nio.ch.IOUtil.makePipe(Native Method)
at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
at java.nio.channels.Selector.open(Selector.java:227)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:142)
```
indicating that there is a file descriptor leak somewhere in the metering code.  In addition, the memory and load plots for the machine seem to confirm this behavior, with a slow(ish) memory leak and then the load increasing dramatically when the free memory is exhausted.  The plots are below.  The metering was started at 15:26 UTC and the Elasticsearch server crashed around 20:40 UTC. 

![Elasticsearch Machine Load (Metering 15:26 - 20:40 UTC)](https://user-images.githubusercontent.com/490506/30731587-977198bc-9f6e-11e7-8e84-d5ba8e713adb.png)

![Elasticsearch Machine Memory (Metering 15:26 - 20:40 UTC](https://user-images.githubusercontent.com/490506/30731609-af826b70-9f6e-11e7-86c4-39a6ddcec0cd.png)

**Comment by elegoff** [comment]
The potential fix of for the metering service crash of Elasticsearch is followed in https://github.com/SixSq/tasklist/issues/1319
