### ISSUE TITLE
ss-config command fail to connect to ES in v3.39

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1285]
While using ss-config to change the SlipStream version after upgrading Nuvla got the following:
```
ss-config configuration-slipstream.edn
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
10:23:48.817 [elasticsearch[_client_][transport_client_boss][T#1]] ERROR org.elasticsearch.transport.netty4.Netty4Utils - fatal error on the network layer
	at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:140)
	at org.elasticsearch.transport.netty4.Netty4Transport$ClientChannelInitializer.exceptionCaught(Netty4Transport.java:487)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:117)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-1" java.lang.NoSuchMethodError: io.netty.handler.codec.ByteToMessageDecoder.ensureNotSharable()V
	at io.netty.handler.codec.ByteToMessageDecoder.<init>(ByteToMessageDecoder.java:141)
	at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.<init>(Netty4SizeHeaderFrameDecoder.java:31)
	at org.elasticsearch.transport.netty4.Netty4Transport$ClientChannelInitializer.initChannel(Netty4Transport.java:480)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{iTtoRLTYR1uCPc15AC1scA}{159.100.240.234}{159.100.240.234:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:344)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:242)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:356)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:710)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at com.sixsq.slipstream.db.es.utils$cluster_health.invokeStatic(utils.clj:209)
	at com.sixsq.slipstream.db.es.utils$cluster_health.invoke(utils.clj:207)
	at com.sixsq.slipstream.db.es.utils$wait_for_cluster.invokeStatic(utils.clj:239)
	at com.sixsq.slipstream.db.es.utils$wait_for_cluster.invoke(utils.clj:237)
	at com.sixsq.slipstream.db.es.binding$wait_client_create_index.invokeStatic(binding.clj:19)
	at com.sixsq.slipstream.db.es.binding$wait_client_create_index.invoke(binding.clj:17)
	at com.sixsq.slipstream.db.es.binding$create_client.invokeStatic(binding.clj:27)
	at com.sixsq.slipstream.db.es.binding$create_client.invoke(binding.clj:25)
	at com.sixsq.slipstream.db.serializers.utils$create_and_set_es_client.invokeStatic(utils.clj:233)
	at com.sixsq.slipstream.db.serializers.utils$create_and_set_es_client.invoke(utils.clj:228)
	at com.sixsq.slipstream.db.serializers.utils$db_client_and_crud_impl.invokeStatic(utils.clj:241)
	at com.sixsq.slipstream.db.serializers.utils$db_client_and_crud_impl.invoke(utils.clj:235)
	at com.sixsq.slipstream.tools.cli.ssconfig$init_db_client.invokeStatic(ssconfig.clj:57)
	at com.sixsq.slipstream.tools.cli.ssconfig$init_db_client.invoke(ssconfig.clj:55)
	at com.sixsq.slipstream.tools.cli.ssconfig$store_to_db.invokeStatic(ssconfig.clj:284)
	at com.sixsq.slipstream.tools.cli.ssconfig$store_to_db.invoke(ssconfig.clj:282)
	at com.sixsq.slipstream.tools.cli.ssconfig$_main.invokeStatic(ssconfig.clj:464)
	at com.sixsq.slipstream.tools.cli.ssconfig$_main.doInvoke(ssconfig.clj:454)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at com.sixsq.slipstream.tools.cli.ssconfig.main(Unknown Source)
```

**Comment by loomis** [comment]
The above failure occurs on Nuvla, but does not occur on a fresh deployment of SlipStream. In fact, the `ss-config` command works and properly updates the version number in the database.  The problem is either related to hand-installed jars or the use of a remote Elasticsearch server.

**Comment by loomis** [comment]
For a SlipStream instance with a remote Elasticsearch database, the `ss-config` command works normally.  Will now check security groups and firewalls to eliminate that option.

**Comment by loomis** [comment]
Not a firewalling issue.  Using the same security group definitions for the test SlipStream instance (with remote Elasticsearch), the `ss-config` command works normally.
