### ISSUE TITLE
Garbage collector stacktrace in log in v3.45 and later

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1404]
From times to time, we have this stack trace inside error log of java server.

```
Exception in thread "async-dispatch-121" org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.sixsq.slipstream.persistence.Run.runtimeParameters, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:575)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:214)
	at org.hibernate.collection.internal.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:376)
	at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:164)
	at com.sixsq.slipstream.statemachine.StateMachine.createNodeExtrinsicState(StateMachine.java:71)
	at com.sixsq.slipstream.statemachine.StateMachine.recreateStateFromRun(StateMachine.java:128)
	at com.sixsq.slipstream.statemachine.StateMachine.<init>(StateMachine.java:64)
	at com.sixsq.slipstream.statemachine.StateMachine.getStateMachine(StateMachine.java:120)
	at com.sixsq.slipstream.statemachine.StateMachine.createStateMachine(StateMachine.java:106)
	at com.sixsq.slipstream.util.Terminator.terminateInsideTransaction(Terminator.java:123)
	at com.sixsq.slipstream.util.Terminator.purgeRun(Terminator.java:109)
	at com.sixsq.slipstream.util.Terminator.purge(Terminator.java:74)
	at slipstream.async.garbage_collector$purge.invokeStatic(garbage_collector.clj:19)
	at slipstream.async.garbage_collector$purge.invoke(garbage_collector.clj:19)
	at slipstream.async.garbage_collector$collect_BANG_$fn__240$state_machine__7658__auto____243$fn__245.invoke(garbage_collector.clj:36)
	at slipstream.async.garbage_collector$collect_BANG_$fn__240$state_machine__7658__auto____243.invoke(garbage_collector.clj:36)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at 




slipstream.async.garbage_collector$collect_BANG_$fn__240.invoke(garbage_collector.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at 



java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by loomis** [comment]
In reviewing the code, the place where the exception is thrown is logically within a JPA transaction (and hence a hibernate Session).  The EntityManager (and Session) is stored within a TheadLocal variable where it can be retrieved by any JPA code accessing the database. This code, however, is started via core.async, which uses a fixed thread pool and shares tasks (even parts of tasks) between those threads. In this case, what is likely happening is that core.async is starting a task on one thread (where the ThreadLocal variables will be set) and completing the task on another.  If the task was completed on a thread where the EntityManager/Session had not been set, then a stack trace like the one given would be the result. Similarly, it would be possible to use the wrong EntityManager/Session to complete a task, although this would not result in a stack trace. 

The first task is to verify this explanation by adding logging to provide the thread identities when the task is started, ended, and at the point of the error.

If this is confirmed, then possible solutions to the problem are:

 - Managing our own processes/threads in clojure either via futures or threads to ensure that the garbage collection tasks always run on a single thread. (That is, remove the use of core.async for tasks involving access to HSQLDB via JPA.)
 - Moving these processes to the job framework, although this might bring additional problems with multiple clients accessing HSQLDB.
