### ISSUE TITLE
ss-config fail because of a ClassNotFoundException HttpCacheContext

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1506]
This happened in the following deployment: https://nuv.la/run/5f88d702-6bc1-4702-a85e-69e506b98d8c

The issue:
`Caused by: java.lang.ClassNotFoundException: org.apache.http.client.cache.HttpCacheContext`
```
+ ss-config -e id=configuration/slipstream -e clientURL=https://159.100.246.222/downloads/slipstreamclient.tgz -e clientBootstrapURL=https://159.100.246.222/downloads/slipstream.bootstrap -e c
onnectorLibcloudURL=https://159.100.246.222/downloads/libcloud.tgz -e serviceURL=https://159.100.246.222 -e connectorOrchPublicSSHKey=/opt/slipstream/server/.ssh/id_rsa.pub -e connectorOrchPri
vateSSHKey=/opt/slipstream/server/.ssh/id_rsa /etc/slipstream/slipstream.edn
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForName(RT.java:2213)
        at clojure.lang.RT.loadClassForName(RT.java:2232)
        at clojure.lang.RT.load(RT.java:450)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:805)
        at clj_http.client$loading__6434__auto____523.invoke(client.clj:1)
        at clj_http.client__init.load(Unknown Source)
        at clj_http.client__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForName(RT.java:2213)
        at clojure.lang.RT.loadClassForName(RT.java:2232)
        at clojure.lang.RT.load(RT.java:450)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:482)
        at com.sixsq.slipstream.tools.cli.utils$loading__6434__auto____521.invoke(utils.clj:1)
        at com.sixsq.slipstream.tools.cli.utils__init.load(Unknown Source)
        at com.sixsq.slipstream.tools.cli.utils__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForName(RT.java:2213)
        at clojure.lang.RT.loadClassForName(RT.java:2232)
        at clojure.lang.RT.load(RT.java:450)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:930)
        at com.sixsq.slipstream.tools.cli.ssconfig$loading__6434__auto____180.invoke(ssconfig.clj:1)
        at com.sixsq.slipstream.tools.cli.ssconfig__init.load(Unknown Source)
        at com.sixsq.slipstream.tools.cli.ssconfig__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForName(RT.java:2213)
        at clojure.lang.RT.loadClassForName(RT.java:2232)
        at clojure.lang.RT.load(RT.java:450)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:381)
        at clojure.lang.Util.loadWithClass(Util.java:250)
        at com.sixsq.slipstream.tools.cli.ssconfig.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.cache.HttpCacheContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2217)
        at clj_http.core$loading__6434__auto____725.invoke(core.clj:1)
        at clj_http.core__init.load(Unknown Source)
        at clj_http.core__init.<clinit>(Unknown Source)
        ... 98 more
```

**Comment by 0xbase12** [comment]
The issue of clj-http appeared after update of dependencies in SlipStreamParent slipstream/SlipStreamParent@1b81a51. 

clj-http got a new dependency on `org.apache.httpcomponents/httpclient-cache`.

The classpath of cimi-tools was ok, but versions in leiningen reports was ok. The call to mvn dependency:tree with verbose option showed that the clj-http 3.1.0 was retrieved and placed in our lib folder. 

After investigation this was due to the parent artifact of cimi-tools (SlipStreamCommunity) which has SlipStream artifact as parent and which defined some clojures dependencies for clj-time clj-http, clj async, expectations... 


I will try to remove as many clj deps as I can from SlipStream artifact and align versions between clj deps and parent deps
