### ISSUE TITLE
cimi service takes too long to start

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1570]
The CIMI service takes an extremely long time to start, sometimes up to 10 minutes on the standard enterprise deployment tests.  This is happening **before** the code tries to initialize the connection to the database and the CIMI resources. 

Determine what is causing this long delay and fix/workaround it.

**Comment by loomis** [comment]
The stack trace from the initialization period contains the following links to our code:
```
[root@machinef985b967-5985-4f90-a616-52a685d9bd14 ~]# su slipstream -c 'jstack -l 26967' | grep -i sixsq
	at com.sixsq.slipstream.auth.utils.sign$loading__6434__auto____604.invoke(sign.clj:1)
	at com.sixsq.slipstream.auth.utils.sign__init.load(Unknown Source)
	at com.sixsq.slipstream.auth.utils.sign__init.<clinit>(Unknown Source)
	at com.sixsq.slipstream.auth.cookies$loading__6434__auto____602.invoke(cookies.clj:1)
	at com.sixsq.slipstream.auth.cookies__init.load(Unknown Source)
	at com.sixsq.slipstream.auth.cookies__init.<clinit>(Unknown Source)
	at com.sixsq.slipstream.auth.internal$eval288$loading__6434__auto____289.invoke(internal.clj:1)
	at com.sixsq.slipstream.auth.internal$eval288.invokeStatic(internal.clj:1)
	at com.sixsq.slipstream.auth.internal$eval288.invoke(internal.clj:1)
	at com.sixsq.slipstream.auth.auth$eval282$loading__6434__auto____283.invoke(auth.clj:1)
	at com.sixsq.slipstream.auth.auth$eval282.invokeStatic(auth.clj:1)
	at com.sixsq.slipstream.auth.auth$eval282.invoke(auth.clj:1)
	at com.sixsq.slipstream.ssclj.app.routes$eval276$loading__6434__auto____277.invoke(routes.clj:1)
	at com.sixsq.slipstream.ssclj.app.routes$eval276.invokeStatic(routes.clj:1)
	at com.sixsq.slipstream.ssclj.app.routes$eval276.invoke(routes.clj:1)
	at com.sixsq.slipstream.ssclj.app.server$eval164$loading__6434__auto____165.invoke(server.clj:1)
	at com.sixsq.slipstream.ssclj.app.server$eval164.invokeStatic(server.clj:1)
	at com.sixsq.slipstream.ssclj.app.server$eval164.invoke(server.clj:1)
	at sixsq.slipstream.server.ring_container$dyn_resolve$fn__390.invoke(ring_container.clj:64)
	at sixsq.slipstream.server.ring_container$dyn_resolve.invokeStatic(ring_container.clj:63)
	at sixsq.slipstream.server.ring_container$dyn_resolve.invoke(ring_container.clj:57)
	at sixsq.slipstream.server.ring_container$start.invokeStatic(ring_container.clj:150)
	at sixsq.slipstream.server.ring_container$start.doInvoke(ring_container.clj:146)
	at sixsq.slipstream.server.ring_container$_main.invokeStatic(ring_container.clj:197)
	at sixsq.slipstream.server.ring_container$_main.doInvoke(ring_container.clj:190)
	at sixsq.slipstream.server.ring_container.main(Unknown Source)
```
This seems to indicate that there is an issue in the cryptographic libraries when initializing a cookie on startup.  (Why the code is actually initializing a cookie is a different question.)  This smelled like an issue related to entropy availability, so the `haveged` entropy generation service was added to the machine.  After initializing and starting this service, the CIMI startup time is more reasonable.

Actions to take:
 * Ensure that `haveged` is enabled and installed via the SlipStream installation/configuration scripts.
 * Understand why the service startup is trying to sign claims related to a cookie.
