### ISSUE TITLE
Protect global runtime parameters from being overwritten via API

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#256]
Certain global parameters of the run should be protected from PUT request.  The obvious candidate is ss:state.

Here is the case of CERN unsetting ss:state parameter, which lead to failure in StateMachine.

```
Caused by: java.lang.IllegalArgumentException: No enum constant com.sixsq.slipstream.statemachine.States.
        at java.lang.Enum.valueOf(Enum.java:236)
        at com.sixsq.slipstream.statemachine.States.valueOf(States.java:26)
        at com.sixsq.slipstream.statemachine.ExtrinsicState.getState(ExtrinsicState.java:86)
        at com.sixsq.slipstream.statemachine.StateFactory.createInstance(StateFactory.java:29)
        at com.sixsq.slipstream.statemachine.StateMachine.recreateStateFromRun(StateMachine.java:129)
        at com.sixsq.slipstream.statemachine.StateMachine.<init>(StateMachine.java:64)
        at com.sixsq.slipstream.statemachine.StateMachine.getStateMachine(StateMachine.java:120)
        at com.sixsq.slipstream.statemachine.StateMachine.createStateMachine(StateMachine.java:106)
        at com.sixsq.slipstream.util.Terminator.terminate(Terminator.java:86)
        at com.sixsq.slipstream.run.RunResource.terminate(RunResource.java:158)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
        ... 70 more

Mar 03, 2015 10:58:27 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-03-03        10:58:27        127.0.0.1       -       127.0.0.1       80      DELETE  /run/bfaff312-fb6b-4dc9-a105-dc1e768ee63c       -       500     14881   0       247     https://bb1.hnx.helix-nebula.eu Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36       https://bb1.hnx.helix-nebula.eu/run/bfaff312-fb6b-4dc9-a105-dc1e768ee63c
```

**Comment by mebster** [comment]
Do you have the list? We could consider not treating them as runtime parameters

**Comment by konstan** [comment]
No list yet.  Will have to come up with it later.
