### ISSUE TITLE
NPE on missing Image reference when launching a deployment

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#27]
Seen on 1.7 Prod.

Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request

Here is the stacktrace.

```
Caused by: java.lang.NullPointerException
        at com.sixsq.slipstream.util.ModuleUriUtil.extractVersion(ModuleUriUtil.java:64)
        at com.sixsq.slipstream.util.ModuleUriUtil.extractVersionFromResourceUri(ModuleUriUtil.java:75)
        at com.sixsq.slipstream.persistence.Module.load(Module.java:100)
        at com.sixsq.slipstream.persistence.ImageModule.load(ImageModule.java:510)
        at com.sixsq.slipstream.run.RunDeploymentFactory.checkImageHasReferenceOrImageId(RunDeploymentFactory.java:96)
        at com.sixsq.slipstream.run.RunDeploymentFactory.checkAllImagesHaveReferenceOrImageId(RunDeploymentFactory.java:70)
        at com.sixsq.slipstream.run.RunDeploymentFactory.validate(RunDeploymentFactory.java:61)
        at com.sixsq.slipstream.run.RunDeploymentFactory.createRun(RunDeploymentFactory.java:54)
        at com.sixsq.slipstream.run.RunFactory.getRun(RunFactory.java:60)
        at com.sixsq.slipstream.run.RunListResource.createRun(RunListResource.java:199)
        at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:491)
        ... 77 more
Jul 24, 2013 9:59:08 PM org.restlet.engine.log.LogFilter afterHandle
INFO: 2013-07-24        21:59:08        90.10.120.133   -       194.158.5.83    443     POST    /run    -       500     123     222     111     https://194.158.5.83    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36 https://194.158.5.83/module/ServiceCatalog/joomla/simple_deployment/102
```

**Comment by schaubl** [comment]
Doesn't apply anymore.
Related to #134.
