### ISSUE TITLE
If SSH priv/pub keys referred from System Configuration are missing server throws NPE

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#43]
If SSH priv/pub keys referred from System Configuration do not exist -- server should nicely report that when launching a deployment instead of failing and showing "java.lang.NullPointerException" in the Abort field. An even better way would probably be an addition of a validation on the configuration "Save".

java.lang.NullPointerException
        at com.sixsq.slipstream.util.FileUtil.fileToString(FileUtil.java:24)
        at com.sixsq.slipstream.connector.ConnectorBase.getPublicSshKey(ConnectorBase.java:308)
        at com.sixsq.slipstream.connector.ConnectorBase.constructScriptObfuscateCommand(ConnectorBase.java:286)
        at com.sixsq.slipstream.connector.abiquo.AbiquoConnector.launch(AbiquoConnector.java:117)
        at com.sixsq.slipstream.run.Launcher$AsyncLauncher.run(Launcher.java:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:679)

**Comment by schaubl** [comment]
Still relevant.
Promoting to Backlog.
