### ISSUE TITLE
Persisting "long" abort messages generates 500 server side

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#483]
PUT on  /run/72af4843-eb30-4ddb-948a-252e3a856b4a/orchestrator-Flexiant-c2:abort  triggers internal server error due to `org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions data exception: string data, right truncation`

Runtime parameters in the global `ss:` space and `<connector>:abort` are treated as all the others on the run.  Probably an exception should be made to the `ss:` parameters and `<connector>:abort` parameter in all the spaces and an extra processing like truncation can be applied.

```
 2015-09-23T07:44:20.120+0100 WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions SQL Error: -3401, SQLState: 22001 
 2015-09-23T07:44:20.124+0100 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions data exception: string data, right truncation 
 2015-09-23T07:44:20.128+0100 INFO org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl release HHH000010: On release of batch it still contained JDBC statements
 2015-09-23T07:44:20.142+0100 WARNING org.restlet.resource.ServerResource doCatch Exception or error caught in server resource 
 
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:575)
        at org.restlet.resource.ServerResource.put(ServerResource.java:1374)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:447)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:683)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
        at org.restlet.resource.Finder.handle(Finder.java:246)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at com.sixsq.slipstream.application.RootApplication$RootRouter.doHandle(RootApplication.java:452)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
        at org.restlet.Application.handle(Application.java:384)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.Component.handle(Component.java:406)
        at org.restlet.Server.handle(Server.java:516)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:72)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1118)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Transaction not active
        at org.hibernate.jpa.internal.TransactionImpl.rollback(TransactionImpl.java:105)
        at com.sixsq.slipstream.persistence.Metadata.store(Metadata.java:149)
        at com.sixsq.slipstream.persistence.Run.setGlobalAbortState(Run.java:173)
        at com.sixsq.slipstream.persistence.Run.abortOrReset(Run.java:158)
        at com.sixsq.slipstream.run.RuntimeParameterResource.abortOrReset(RuntimeParameterResource.java:98)
        at com.sixsq.slipstream.run.RuntimeParameterResource.update(RuntimeParameterResource.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
        ... 75 more
2015-09-23T07:44:20.210+0100 INFO org.restlet.engine.log.LogFilter afterHandle 2015-09-23       07:44:20        127.0.0.1       -       127.0.0.1       80      PUT     /run/72af4843-eb30-4ddb-948a-252e3a856b4a/orchestrator-Flexiant-c2:abort        ignoreabort=true        500     121     728148  1987    https://109.231.126.66  Python-httplib2/0.7.4 (gzip)    - 
```

**Comment by schaubl** [comment]
The limit defined in the [code](https://github.com/slipstream/SlipStreamServer/blob/ae7c8b6f4decdd0038c762fc27f454cf4999d6e9/jar-persistence/src/main/java/com/sixsq/slipstream/persistence/RuntimeParameter.java#L227) is `4096`.
It was increased from `1024` to  `4096` by @loomis on 9 Sep 2014 with [this commit](https://github.com/slipstream/SlipStreamServer/commit/ae7c8b6f4decdd0038c762fc27f454cf4999d6e9).
But there is a [migration script](https://github.com/slipstream/SlipStreamServer/blob/master/rpm/src/main/migrations/010_varchar_size_fix_3.sql) created on 15 Dec 2014 by @schaubl which increase this value to `65536`.

So it seems that the later increase wasn't reported in the code.

**Comment by schaubl** [comment]
On my dev SlipStream I searched in the database all runtimeparameters with a value longer than `4096` charcters and I found some.
All of them were abort messages except one which was `testclient:ids` for a Run with 1501 VMs.

So in the case of huge Runs we need a limit greater than `4096`.
