### ISSUE TITLE
jar-async build fails with latest core.async version

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#532]
When upgrading to the latest core.async version (0.2.374) from the current version (0.2.371), the jar-async build fails.  The stack trace is the following:
```
Compiling slipstream.async.collector to /Users/loomis/Documents/code/SlipStream/SlipStreamBootstrap/SlipStreamServer/jar-async/target/classes
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(jvm.clj:9:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3628)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile1(Compiler.java:7313)
	at clojure.lang.Compiler.compile(Compiler.java:7390)
	at clojure.lang.RT.compile(RT.java:399)
	at clojure.lang.RT.load(RT.java:444)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at clojure.core.async.impl.ioc_macros$loading__5340__auto____437.invoke(ioc_macros.clj:12)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile1(Compiler.java:7313)
	at clojure.lang.Compiler.compile(Compiler.java:7390)
	at clojure.lang.RT.compile(RT.java:399)
	at clojure.lang.RT.load(RT.java:444)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at clojure.core.async$loading__5340__auto____17.invoke(async.clj:9)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile1(Compiler.java:7313)
	at clojure.lang.Compiler.compile(Compiler.java:7390)
	at clojure.lang.RT.compile(RT.java:399)
	at clojure.lang.RT.load(RT.java:444)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at slipstream.async.collector$loading__5340__auto____1.invoke(collector.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile1(Compiler.java:7313)
	at clojure.lang.Compiler.compile(Compiler.java:7390)
	at clojure.lang.RT.compile(RT.java:399)
	at clojure.lang.RT.load(RT.java:444)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$compile$fn__5453.invoke(core.clj:5877)
	at clojure.core$compile.invoke(core.clj:5876)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Compile.main(Compile.java:67)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.core$use.doInvoke(core.clj:5843)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.tools.reader.reader_types$loading__5340__auto____1271.invoke(reader_types.clj:9)
	at clojure.tools.reader.reader_types__init.load(Unknown Source)
	at clojure.tools.reader.reader_types__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.core$use.doInvoke(core.clj:5843)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.tools.reader$loading__5340__auto____1483.invoke(reader.clj:9)
	at clojure.tools.reader__init.load(Unknown Source)
	at clojure.tools.reader__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at clojure.tools.analyzer.jvm$loading__5340__auto____931.invoke(jvm.clj:9)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
	... 83 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/reader/impl/ExceptionInfo__init.class or clojure/tools/reader/impl/ExceptionInfo.clj on classpath.
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.tools.reader.impl.utils$loading__5340__auto____1273.invoke(utils.clj:9)
	at clojure.tools.reader.impl.utils__init.load(Unknown Source)
	at clojure.tools.reader.impl.utils__init.<clinit>(Unknown Source)
	... 153 more
```

**Comment by rbf** [comment]
@loomis I can reproduce the error described here by changing the `core-async` version to `v0.2.371` in the [`SlipStream/pom.xml`](https://github.com/slipstream/SlipStream/blob/9d717f9657af7404f8e52aea50dfafa0ad348e9d/pom.xml#L878) file.

I've not yet found the error but it might be related to the version of the `clojurescript` dependency, since it has been upgraded on `v0.2.374`, see https://github.com/clojure/core.async/compare/v0.2.371...v0.2.374.

I've not been able to find if there is a `clojurescript` version defined in the `SlipStream` or `SlipStreamServer` projects. I'll check with you on Monday.

**Comment by rbf** [comment]
@loomis After some debugging with @st, we found out that the offender dependency was `org.clojure/tools.reader`. A wrong version of it was probably required by another dependency. Following some advise found in internet on similar issues, we excluded the mentioned dependency from the main `pom.xml` (see commit https://github.com/slipstream/SlipStream/commit/22f5735a03db0ec868c51a5058ff034eb31dab88 above):

```xml
        <exclusions>
          <exclusion>
            <groupId>org.clojure</groupId>
            <artifactId>tools.reader</artifactId>
          </exclusion>
        </exclusions>
```

**Comment by loomis** [comment]
Great.  Please also update the entry in `clojure-deps/src/main/resources/default-deps.edn`.   When all of the clojure-based modules are updated to use `boot`, the clojure dependencies will be removed from the `pom.xml` file.

**Comment by rbf** [comment]
@loomis Done. I updated the version number of core.async in `clojure-deps/src/main/resources/default-deps.edn`. The change is included in the same PR https://github.com/slipstream/SlipStream/pull/124.

However, I've not added the exclusion rule. Is it also required there?
