### ISSUE TITLE
scale down is not working

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#542]
The scale down function is not working correctly.  The action is successful on the API, but the nodes themselves are never removed.  One one scale down action a python error was raised, but I couldn't find the traceback (see attached file). 

![error-message-scale-down](https://cloud.githubusercontent.com/assets/490506/11324771/dfd2feae-913b-11e5-9e8a-b48c0d0736e1.png)

**Comment by konstan** [comment]
This is the result of this change in the client code: https://github.com/slipstream/SlipStreamClient/commit/8d2699862098e5d1defe9e267f46b12ccd14ba1d

**Comment by konstan** [comment]
The stack trace is as always available in the reports from orchestrator:

```
: 2015-11-22T15:51:35Z : 
===============
==== Ready ====
===============

: 2015-11-22T15:57:37Z : 
======================
==== Provisioning ====
======================

: 2015-11-22T15:57:37Z : 
==== Starting instances

: 2015-11-22T15:57:37Z : 
    No node instances to start [2015-11-22T15:57:37Z].

: 2015-11-22T15:57:38Z : 
ERROR: Error executing node, with detail: get_node_instances_in_scale_state() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/executors/MachineExecutor.py", line 91, in _execute_state
    getattr(self, method_name)()
  File "/opt/slipstream/client/lib/slipstream/util.py", line 105, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 41, in onProvisioning
    self._stop_instances()
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 84, in _stop_instances
    self._wait_pre_scale_done_if_horizontal_scale_down()
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 90, in _wait_pre_scale_done_if_horizontal_scale_down
    self.wrapper.SCALE_STATE_REMOVING, self.wrapper._get_cloud_service_name())
TypeError: get_node_instances_in_scale_state() takes exactly 2 arguments (3 given)

...

: 2015-11-22T15:57:38Z : 
=========================
==== Sending reports ====
=========================
Uploading report to: https://nuv.la/reports/ced28f99-e08b-4667-86db-73f53c059c58

: 2015-11-22T15:57:53Z : 
===================
==== Executing ====
===================
```
