### ISSUE TITLE
Horizontal scaling down fails on authn service side

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#567]
```
2015-12-02 14:17:49,564 INFO  - :delete /run/d775a1bb-0e2c-4a2a-af11-9ea78cfed3e3/testclient [no-authn-info] ?no-query-string java.io.ByteArrayInputStream@316a4a72
2015-12-02 14:17:49,566 ERROR - error in HTTP handler
java.lang.IllegalArgumentException: No matching method found: setEntity for class org.apache.http.client.methods.HttpDelete
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at puppetlabs.http.client.async$fn__9585$request_with_client__9586$fn__9587.invoke(async.clj:398)
        at puppetlabs.http.client.async$fn__9585$request_with_client__9586.invoke(async.clj:362)
        at puppetlabs.http.client.sync$request_with_client.invoke(sync.clj:29)
        at puppetlabs.http.client.sync$request.invoke(sync.clj:40)
        at puppetlabs.http.client.sync$delete.invoke(sync.clj:92)
        at com.sixsq.slipstream.ssclj.middleware.proxy_redirect$redirect.invoke(proxy_redirect.clj:108)
        at com.sixsq.slipstream.ssclj.middleware.proxy_redirect$wrap_proxy_redirect$fn__302.invoke(proxy_redirect.clj:128)
        at ring.middleware.cookies$wrap_cookies$fn__2282.invoke(cookies.clj:161)
        at com.sixsq.slipstream.ssclj.middleware.logger$wrap_logger$fn__107.invoke(logger.clj:41)
        at aleph.http.server$wrap_stream__GT_input_stream$fn__6577.invoke(server.clj:403)
        at aleph.http.server$handle_request$fn__6495$f__2914__auto____6496.invoke(server.clj:153)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:49)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by konstan** [comment]
Client-server exchange.

```
$ ss-node-remove -vvv -u test -p 85e56427ff41 --endpoint https://185.19.30.134 d775a1bb-0e2c-4a2a-af11-9ea78cfed3e3 testclient 1

: 2015-12-02T14:24:51Z :
    Calling: '/usr/local/bin/ss-node-remove -vvv -u test -p 85e56427ff41 --endpoint https://185.19.30.134 d775a1bb-0e2c-4a2a-af11-9ea78cfed3e3 testclient 1'

: 2015-12-02T14:24:51Z :
    Removing node instances: 1...
1

: 2015-12-02T14:24:51Z :
    Contacting the server with DELETE, at: https://185.19.30.134/run/d775a1bb-0e2c-4a2a-af11-9ea78cfed3e3/testclient

: 2015-12-02T14:24:51Z :
    Using basic authentication
connect: (185.19.30.134, 443)
send: 'DELETE /run/d775a1bb-0e2c-4a2a-af11-9ea78cfed3e3/testclient HTTP/1.1\r\nHost: 185.19.30.134\r\nContent-Length: 5\r\naccept-encoding: gzip, deflate\r\ncontent-type: application/xml\r\naccept: applic
ation/xml\r\nauthorization: Basic dGVzdDo4NWU1NjQyN2ZmNDE=\r\nuser-agent: Python-httplib2/0.9.2 (gzip)\r\n\r\nids=1'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Server: nginx/1.8.0
header: Date: Wed, 02 Dec 2015 14:24:52 GMT
header: Content-Type: text/plain; charset=utf-8
header: Content-Length: 1333
header: Connection: keep-alive

: 2015-12-02T14:24:52Z :
    Received response: {'status': '500', 'content-length': '1333', 'server': 'nginx/1.8.0', 'connection': 'keep-alive', 'date': 'Wed, 02 Dec 2015 14:24:52 GMT', 'content-type': 'text/plain; charset=utf-8'
}
with content:
 java.lang.IllegalArgumentException: No matching method found: setEntity for class org.apache.http.client.methods.HttpDelete
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at puppetlabs.http.client.async$fn__9585$request_with_client__9586$fn__9587.invoke(async.clj:398)
        at puppetlabs.http.client.async$fn__9585$request_with_client__9586.invoke(async.clj:362)
        at puppetlabs.http.client.sync$request_with_client.invoke(sync.clj:29)
        at puppetlabs.http.client.sync$request.invoke(sync.clj:40)
        at puppetlabs.http.client.sync$delete.invoke(sync.clj:92)
        at com.sixsq.slipstream.ssclj.middleware.proxy_redirect$redirect.invoke(proxy_redirect.clj:108)
        at com.sixsq.slipstream.ssclj.middleware.proxy_redirect$wrap_proxy_redirect$fn__302.invoke(proxy_redirect.clj:128)
        at ring.middleware.cookies$wrap_cookies$fn__2282.invoke(cookies.clj:161)
        at com.sixsq.slipstream.ssclj.middleware.logger$wrap_logger$fn__107.invoke(logger.clj:41)
        at aleph.http.server$wrap_stream__GT_input_stream$fn__6577.invoke(server.clj:403)
        at aleph.http.server$handle_request$fn__6495$f__2914__auto____6496.invoke(server.clj:153)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:49)
        at java.lang.Thread.run(Thread.java:745)
...
```

**Comment by konstan** [comment]
Workaround is to bypass `authn` service with `nginx` pointing directly to SS service.

**Comment by konstan** [comment]
Because workaround exists - moved to milestone v2.21.

**Comment by st** [comment]
More precisely, only the proxy redirection (clojure server upfront proxies everything except `api` and `auth`) is skipped.
The clojure server has 3 responsibilities:
- api  (clojure REST resources, event, usage, ...)
- auth (create a signed token)
- proxy to Java Server.

**Comment by st** [comment]
https://tickets.puppetlabs.com/browse/TK-66
Looks like puppet labs http client does not like body when HTTP verb is delete.

**Comment by st** [comment]
http://stackoverflow.com/questions/14323716/restful-alternatives-to-delete-request-body

**Comment by loomis** [comment]
The problems with the proxy redirection (at least with aleph and clj-http) seem to be coming mostly from the documented (but unexpected) throwing of exceptions on http error statuses (e.g. 404, but also including 304!).  Information about this behavior can be found on the [clj-http]() page in the "Exceptions" section. For both aleph and clj-http, the response map is thrown as the data in the ExceptionInfo object. 

When using aleph, this problem with throwing is further compounded by the fact that aleph produces "deferred" values (essentially a promise or future) even in the thrown exceptions, causing problems with dereferencing of unrealized values.

This behavior can be turned off by adding `{:throw-exceptions false}` to the request options map.  This will cause the http error responses to be treated as normal responses.

**Comment by loomis** [comment]
The options also need to be updated to be consistent with the aleph and clj-http libraries:
```
{:throw-exceptions false ;; as described above
 :force-redirects false
 :follow-redirects false
 :socket-timeout 60000
 :conn-timeout 60000
 :pool-timeout 60000 ;; only for aleph
}
```
The pool time out for clj-http can be controlled by creating and passing a connection pool with the appropriate connections.
