### ISSUE TITLE
SS 2.20 service process crashes after running for couple of days with cred-cache and OCCI connector

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#603]
OCCI test instance https://185.19.30.27/.  This happens already for the fourth time.  It's a 2CPU/2GB RAM VM on Exoscale.  It may well be related to the too low memory capacity.  However, the service is not heavily used - couple of deployments a day.

```
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]# rpm -qa | grep slipstream
slipstream-useradd-community-2.20-0.el6.noarch
slipstream-server-community-2.20-0.el6.noarch
slipstream-hsqldb-community-2.20-0.el6.noarch
slipstream-client-community-2.20-0.el6.noarch
slipstream-ssclj-community-2.20-0.el6.noarch
slipstream-repos-2.2-1.noarch
slipstream-connector-occi-community-2.20-0.el6.noarch
slipstream-graphite-community-2.20-0.el6.noarch
libcloud-slipstream-downloads-community-2.20-0.el6.noarch
slipstream-server-nginx-conf-community-2.20-0.el6.noarch
slipstream-connector-occi-python-community-2.20-0.el6.noarch
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]#
```

There are no traces of the crash in any of the SS service log files.

```
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]# lsof /opt/slipstream/server/logs/*.log
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]#
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]# tail -3 /opt/slipstream/server/logs/slipstream.log.0
 2016-01-19T18:29:56.361+0000 INFO com.sixsq.slipstream.connector.VmsClassifier classify Classify [new, gone, staying] [0, 0, 0]
 2016-01-19T18:29:56.365+0000 INFO com.sixsq.slipstream.util.Logger info [proxytest/fedcloud-ifca] 1453228196365  (2071 ms) : Number of VMs collected = 0
 [root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]#
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]# service slipstream status
Checking arguments to Jetty:
START_INI      =  /opt/slipstream/server/start.ini
START_D        =  /opt/slipstream/server/start.d
JETTY_HOME     =  /opt/slipstream/server
JETTY_BASE     =  /opt/slipstream/server
JETTY_CONF     =  /opt/slipstream/server/etc/jetty.conf
JETTY_PID      =  /var/run/slipstream.pid
JETTY_START    =  /opt/slipstream/server/start.jar
JETTY_LOGS     =  /opt/slipstream/server/logs
JETTY_STATE    =  /opt/slipstream/server/slipstream.state
CLASSPATH      =
JAVA           =  /etc/alternatives/jre_1.8.0/bin/java
JAVA_OPTIONS   =  -Djetty.logging.dir=/opt/slipstream/server/logs -Djetty.home=/opt/slipstream/server -Djetty.base=/opt/slipstream/server -Djava.io.tmpdir=/opt/slipstream/server/tmp
JETTY_ARGS     =  -Dslipstream.ui.util.localization.lang-default=en-US jetty.state=/opt/slipstream/server/slipstream.state --exec -Dslipstream.config.file=/etc/slipstream/slipstream.conf jetty-logging-ss.xml jetty-started.xml
RUN_CMD        =  /etc/alternatives/jre_1.8.0/bin/java -Djetty.logging.dir=/opt/slipstream/server/logs -Djetty.home=/opt/slipstream/server -Djetty.base=/opt/slipstream/server -Djava.io.tmpdir=/opt/slipstream/server/tmp -jar /opt/slipstream/server/start.jar -Dslipstream.ui.util.localization.lang-default=en-US jetty.state=/opt/slipstream/server/slipstream.state --exec -Dslipstream.config.file=/etc/slipstream/slipstream.conf jetty-logging-ss.xml jetty-started.xml

[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]#
```

When the service is down, user sees the raw stacktrace on UI https://185.19.30.27  (IMHO, this deserves a separate improvement request.)

```
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
	at java.lang.Thread.run(Thread.java:745)
```

It's the raw stacktrace as it goes to `/var/log/slipstream/ssclj/ssclj.log`

```
2016-01-20 11:09:08,108 INFO  - :get /run/a5740197-347b-4d54-af1d-fb098a450a09 [no-authn-info] ?no-query-string no-body
2016-01-20 11:09:08,110 ERROR - error in HTTP handler
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by konstan** [comment]
Connected to https://github.com/slipstream/SlipStreamConnectors/issues/67 

Closing this issue.  This was due to 2GB to be too few memory for running service with the cred.-cache.

```
[root@machinef81e00ff-a18a-43b4-afa3-4c67c9e80a47 ~]# 
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f2d00000, 56098816, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 56098816 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/slipstream/server/hs_err_pid20477.log
```
