### ISSUE TITLE
compilation failure for .../migration/script.clj

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#729]
On the Jenkins server, the build (`mvn clean compile`) fails because the compiler cannot find the `Binding` protocol.  The (partial) stack trace is: 
```
Compiling com.sixsq.slipstream.ssclj.migrate.script to /var/lib/jenkins/workspace/Community_Build/SlipStreamServer/ssclj/jar/target/classes
Exception in thread "main" java.lang.ClassNotFoundException: com.sixsq.slipstream.ssclj.db.binding.Binding, compiling:(es_binding.clj:4:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
[snip]
```
Whether this fails depends on the order of the compilation.

**Comment by loomis** [comment]
The problem is that the `Binding` protocol is imported as a Java interface rather than being required as a clojure namespace.  If something else hasn't been compiled and implicitly created the Binding class, then the compilation won't look for the clojure source.
