### ISSUE TITLE
Red status for Elastic Search on nuvlabox

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#790]
The ES status is `red` (randomly) causing the startup of SlipStream SSCLJ server to fail.

Some useful ES commands 

```
curl -XGET 'localhost:9200/_cluster/health'
curl -XGET 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
```

**Comment by st** [comment]
Exception at startup
```
Jul 29 02:52:15 localhost java: Exception in thread "main" clojure.lang.ExceptionInfo: status is not accepted {:status "RED"}
Jul 29 02:52:15 localhost java: at clojure.core$ex_info.invokeStatic(core.clj:4617)
Jul 29 02:52:15 localhost java: at clojure.core$ex_info.invoke(core.clj:4617)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_util$throw_if_cluster_not_healthy.invokeStatic(es_util.clj:193)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_util$throw_if_cluster_not_healthy.invoke(es_util.clj:190)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_util$wait_for_cluster.invokeStatic(es_util.clj:232)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_util$wait_for_cluster.invoke(es_util.clj:228)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_binding$wait_client_create_index.invokeStatic(es_binding.clj:21)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_binding$wait_client_create_index.invoke(es_binding.clj:19)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_binding$create_client.invokeStatic(es_binding.clj:29)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.es.es_binding$create_client.invoke(es_binding.clj:27)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.server$start.invokeStatic(server.clj:73)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.server$start.invoke(server.clj:62)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.server$start.invokeStatic(server.clj:66)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.server$start.invoke(server.clj:62)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.main$_main.invokeStatic(main.clj:37)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.main$_main.doInvoke(main.clj:31)
Jul 29 02:52:15 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:137)
Jul 29 02:52:15 localhost java: at com.sixsq.slipstream.ssclj.app.main.main(Unknown Source)
Jul 29 02:52:16 localhost systemd: ssclj.service: main process exited, code=exited, status=1/FAILURE
```
