### ISSUE TITLE
after sometime collector fails to insert user/connector pairs for "online users"

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#849]
It might be related to this issue

```
Exception in thread "async-dispatch-3" java.lang.ArithmeticException: Divide by zero
        at clojure.lang.Numbers.divide(Numbers.java:158)
        at clojure.lang.Numbers.divide(Numbers.java:3788)
        at slipstream.async.collector$insert_collection_requests.invokeStatic(collector.clj:245)
        at slipstream.async.collector$insert_collection_requests.invoke(collector.clj:240)
        at slipstream.async.collector$collect_writers$fn__6565$state_machine__3990__auto____6566$fn__6568.invoke(collector.clj:257)
        at slipstream.async.collector$collect_writers$fn__6565$state_machine__3990__auto____6566.invoke(collector.clj:257)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:1012)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1011)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:1016)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1014)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__4006.invoke(ioc_macros.clj:1025)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__354.invoke(channels.clj:265)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by konstan** [comment]
Found in the stdout/err log of the server.  

`2016_09_12.stderrout.log` for the issue above.
